<div class="jumbotron jumbotron-fluid " style="padding:20px">
    <div class="container" style="">
        {{--                    <h1>Bootstrap Tutorial</h1>--}}
        <div data-v-50d8709d="" role="alert" class="el-alert disclaimer el-alert--info is-light">
            <!----><div class="el-alert__content"><span class="el-alert__title is-bold"><b class="text-dark">Disclaimer:</b></span><p class="el-alert__description"><p data-v-50d8709d=""><strong data-v-50d8709d="">Serenus.AI™</strong> ("System") is a system designed to assist professionals with their control of the medical procedures decision-making process before medical procedures. In no way, shall the System be used as a decisive factor for a medical procedure and the medical practitioners shall always have sole discretion whether or not to perform a medical procedure. In no event shall Serenus.AI Ltd. be responsible or liable for any damage caused or sustained in connection with the performance or a decision not to perform a medical procedure connection with the use of the System. </p> <p data-v-50d8709d=""><strong data-v-50d8709d="">Intellectual Property retention:</strong> All rights, title and interest in and to the Serenus.AI™ trade name and the System, including without limitation,software, algorithm, reports , user interface, design , questionnaire and/or any material related thereto vest solely in Serenus.AI Ltd.
                </p> <p data-v-50d8709d=""><strong data-v-50d8709d="">Serenus.AI Confidential and Proprietary Information:</strong> The user undertakes to maintain in strict confidentiality all information relating to the system among others its technical data, its commercial data, its algorithm, its methods, its knowledge, its data, its machine learning methods and modules, its diagrams and any further information whether written or oral ("Confidential וnformation”). The confidential Information shall not be used in any way directly or indirectly or disclosed by the user. The user shall not make any copy of any part of the system and shall return any material connected with the system to the company upon the end of the usage.
                </p> <p data-v-50d8709d=""><strong data-v-50d8709d="">Any questions?</strong> Feel free to contact us at: +972-54-3155222 | info@serenusai.com
                </p> <!----><i class="el-alert__closebtn el-icon-close"></i></div></div>
    </div>
</div>
